### ISSUE TITLE
How to compile the kernel

### ISSUE THREAD

**Issue by wutianze** [google/ghost-kernel#10]
Hi,
I want to try this kernel, but don't know which module is needed(.config file). When compiling ghost-kernel in Ubuntu22.04, I copy the .config file of kernel 6.2.0-36-generic. Here are the errors I met:

The first error is "No rule to make target 'debian/canonical-certs.pem', needed by 'certs/x509_certificate_list'". So I disable the SYSTEM_REVOCATION_KEYS,  and it works.
The second error is "BTFIDS  vmlinux FAILED: load BTF from vmlinux: Invalid argument". I disabled BTF generation in the kernel configuration (CONFIG_DEBUG_INFO_BTF=n) this time, and it works.

Although it is successfully compiled, I am worried if it is OK to disable these two options. Especially for the BTF, which is important for eBPF I think.

Could you help me with this? Thank you so much.

**Comment by jackhumphries** [comment]
Hi,

Since this is presumably for a test environment, disabling `SYSTEM_REVOCATION_KEYS` sounds fine. Disabling `CONFIG_DEBUG_INFO_BTF` is also fine as well, since I think you only really need that set if you are generating a vmlinux header for BPF development, which you shouldn't need to do for the ghOSt project. BPF programs should run just fine with this option disabled.

Jack
