### ISSUE TITLE
Tickless Scheduling 

### ISSUE THREAD

**Issue by aghari19** [google/ghost-kernel#9]
Hello, 

On the userspaace tests folder I have a test file that schedules 1000 threads in sometime x. I would like to know if it were done in tickless mode how long it would take. I am running in centralized mode but do not know how to utilize the tickless methods written in the kernel to learn about the time taken to schedule 1000 threads in tickless mode. 

Can someone help with pointers on how I can achieve this. 
Thank you, 
Haritha

**Comment by dohyunkim-dev** [comment]
Hi Haritha,

Thanks for reaching out to us. You can try to enable/disable tickless mode in the kernel by setting CONFIG_HZ_PERIODIC, CONFIG_NO_HZ_IDLE, and CONFIG_NO_HZ_FULL (Ref: https://lwn.net/Articles/549580/) in kernel. ghOSt does not produce tick by itself and will only passively deliver what's generated inside the kernel. You can set whether you would like to deliver tick messages using CpuTickConfig https://github.com/google/ghost-userspace/blob/c6c811b8f37c2aa683baac11dd891f8e1274f6f4/lib/enclave.h#L36. If kAllTicks is set, ghOSt agents will get all the ticks generated by the kernel. However, if the kernel is set not to generate any tick at all (e.g., CONFIG_NO_HZ_FULL), the agent will not be able get a tick at all even with kAllTicks because the tick won't be produced at all.

Thanks,
Dohyun
